from binance.enums import *

ASSET = 'BTC'
FIAT = 'USDT'
SYMBOL = ASSET + FIAT
IS_REAL_TRADER = False
INTERVAL = KLINE_INTERVAL_1HOUR
THREADS = dict()
PUBLIC_KEY = 'vcMdCj0x8aBQDqfhdtvINsXVqfvDbNOtwVYQyTdJtzKEKUY1nO90WmHidBx9stBB'
SECRET_KEY = 'USuTMTotFMlRhiBWvjqfMrofvDVG0XtnuGeAdZnkLCV6WaEzwtN420VfjUrDwi4c'
TELEGRAM_ID = 1369437188

