from binance.enums import *

ASSET = 'BTC'
FIAT = 'USDT'
SYMBOL = ASSET + FIAT
IS_REAL_TRADER = False
IS_BACKTEST = False
INTERVALS = [KLINE_INTERVAL_15MINUTE, KLINE_INTERVAL_5MINUTE, KLINE_INTERVAL_1MINUTE]
THREADS = dict()
PUBLIC_KEY = 'L0StmJktnhhUzyVEa63qcUAugrnXMrw0Ye43eYMOB4ZjQ59F2fYeevTJK4VkzDMg'
SECRET_KEY = 'MOIijqyyq5POAOjQ9UncjYQXbGIb1TeWwFGMYyYXeCcHV6cEWkIQS6sppVNFUc90'
TELEGRAM_ID = [1369437188]

